// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv69KphwNM0f7tTZIW7nghW8W2SJzRl1U',
    appId: '1:723111380917:web:3442be34863bad82bb3bfc',
    messagingSenderId: '723111380917',
    projectId: 'dummy-b8892',
    authDomain: 'dummy-b8892.firebaseapp.com',
    storageBucket: 'dummy-b8892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI0OdvTeZyxLSdxzXuhbCXY2xGnyATJ80',
    appId: '1:723111380917:ios:54582c309a262212bb3bfc',
    messagingSenderId: '723111380917',
    projectId: 'dummy-b8892',
    storageBucket: 'dummy-b8892.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI0OdvTeZyxLSdxzXuhbCXY2xGnyATJ80',
    appId: '1:723111380917:ios:54582c309a262212bb3bfc',
    messagingSenderId: '723111380917',
    projectId: 'dummy-b8892',
    storageBucket: 'dummy-b8892.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv69KphwNM0f7tTZIW7nghW8W2SJzRl1U',
    appId: '1:723111380917:web:805903d98dc03a1abb3bfc',
    messagingSenderId: '723111380917',
    projectId: 'dummy-b8892',
    authDomain: 'dummy-b8892.firebaseapp.com',
    storageBucket: 'dummy-b8892.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-YYnZBdpKNFbvVLnjE2gosXi8m3_htmg',
    appId: '1:723111380917:android:f04510d51505b0c9bb3bfc',
    messagingSenderId: '723111380917',
    projectId: 'dummy-b8892',
    storageBucket: 'dummy-b8892.firebasestorage.app',
  );
}
